services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./.env:/app/.env
      - ./rule.html:/app/rule.html
  
  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
